version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: agenderDB
    ports:
      - 27017:27017
    
  web:
    image: kailash6969/agender-1:latest
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration

  migration:
    image: kailash6969/agender-1:latest
    command: python manage.py migrate
    links:
        - mongodb
    depends_on:
        - mongodb
        - makemigrations

  makemigrations:
    image: kailash6969/agender-1:latest
    command: python manage.py makemigrations
    links:
        - mongodb
    depends_on:
        - mongodb