# Generated by Django 3.2.9 on 2021-11-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='agender',
        ),
    ]
