# Generated by Django 3.2.9 on 2021-11-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
