# Generated by Django 3.2.9 on 2021-11-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_alter_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
