# Generated by Django 3.1.12 on 2021-12-25 23:03

from django.db import migrations, models
import djongo.models.fields
import login_signup.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('fields', djongo.models.fields.ArrayField(model_container=login_signup.models.Field)),
            ],
        ),
        migrations.CreateModel(
            name='response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', djongo.models.fields.ArrayField(model_container=login_signup.models.Field)),
            ],
        ),
    ]
