# Generated by Django 3.1.12 on 2021-12-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='form_id',
            field=models.IntegerField(default=0),
        ),
    ]
